name: test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  corvus_macos:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
      with:
        swift-version: "5.2.0"
    - name: Xcode 11.4
      run: sudo xcode-select -s /Applications/Xcode_11.4.app/Contents/Developer
    - name: Xcode version check
      run: xcodebuild -version
    - name: Check version
      run: swift --version
    - name: Build
      run: swift build
    - name: Test
      run: swift test --enable-test-discovery --sanitize=thread
